# Generated by Django 4.2.7 on 2023-11-15 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Категория')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Фотография')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('master_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Фотография')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('short_description', models.CharField(max_length=200, verbose_name='Краткая информация')),
                ('full_description', models.TextField(verbose_name='Полная информация')),
                ('rating', models.PositiveIntegerField(blank=True, verbose_name='Рейтинг')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
    ]
