# Generated by Django 4.2.7 on 2023-11-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masters',
            name='photo',
            field=models.ImageField(upload_to='images/', verbose_name='Фотография'),
        ),
    ]
