# Generated by Django 4.2.7 on 2024-03-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_masters_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
    ]
