# Generated by Django 4.2.7 on 2024-03-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_alter_users_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_customer',
            field=models.BooleanField(default=True, verbose_name='Клиент'),
        ),
    ]
