# Generated by Django 4.2.7 on 2024-03-14 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_users_is_customer'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
