# Generated by Django 4.2.7 on 2024-04-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_alter_users_managers_remove_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_customer',
            field=models.BooleanField(default=True, help_text='Уберите отметку, если пользователь является сотрудником салона', verbose_name='Клиент'),
        ),
    ]
