# Generated by Django 4.2.7 on 2024-05-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_weekday_remove_masters_rating_masters_weekend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekday',
            options={'verbose_name': 'Выходной', 'verbose_name_plural': 'Выходные'},
        ),
    ]
