# Generated by Django 4.2.7 on 2024-05-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_alter_weekday_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masters',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='masters',
            name='salary',
        ),
    ]
