# Generated by Django 4.2.7 on 2024-04-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_appointments_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('Отклонено', 'Declined'), ('Принято', 'Accepted'), ('Ожидает ответ', 'Waiting')], default='Ожидает ответ', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
