# Generated by Django 4.2.7 on 2024-04-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_appointments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('0', 'Отклонено'), ('1', 'Принято'), ('2', 'Ожидает ответ')], default='2', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
