# Generated by Django 4.2.7 on 2024-05-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_appointments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
