# Generated by Django 4.2.7 on 2024-05-24 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_appointments_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='time',
        ),
        migrations.AddField(
            model_name='appointments',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 20, 58, 23, 586874), verbose_name='Дата и время'),
        ),
    ]
