# Generated by Django 4.2.7 on 2024-05-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_appointments_datetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
    ]
