# Generated by Django 4.2.7 on 2024-05-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True, verbose_name='URL'),
        ),
    ]
