# Generated by Django 4.2.7 on 2024-05-12 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_cart_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 12, 12, 54, 48, 915920), verbose_name='Дата оформления'),
        ),
    ]
