# Generated by Django 4.2.7 on 2024-05-12 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_cart_quantity_alter_cart_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='total_sum',
        ),
        migrations.AlterField(
            model_name='cart',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 12, 23, 57, 0, 641077), verbose_name='Дата оформления'),
        ),
    ]
