# Generated by Django 4.2.7 on 2024-05-12 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_cart_order_date_alter_cart_total_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 0, 5, 14, 551971), verbose_name='Дата оформления'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма заказа'),
        ),
    ]
