# Generated by Django 4.2.7 on 2024-05-15 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_cart_order_date_alter_cart_total_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 15, 32, 44, 292004), verbose_name='Дата оформления'),
        ),
    ]
