# Generated by Django 4.2.7 on 2024-05-24 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_cart_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 20, 58, 23, 602504), verbose_name='Дата оформления'),
        ),
    ]
