# Generated by Django 4.2.7 on 2024-05-27 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_cart_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 19, 23, 34, 202068), verbose_name='Дата оформления'),
        ),
    ]
