# Generated by Django 4.2.7 on 2024-05-29 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_product_available_alter_cart_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 19, 18, 41, 116726), verbose_name='Дата оформления'),
        ),
    ]
