# Generated by Django 4.2.7 on 2024-06-02 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_cart_order_date_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 11, 24, 8, 999058), verbose_name='Дата оформления'),
        ),
    ]
