# Generated by Django 4.2.7 on 2023-11-15 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration', models.DurationField(verbose_name='Длительность')),
                ('cost', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Стоимость')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Фотография')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
