# Generated by Django 4.2.7 on 2023-11-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('duration', models.DurationField(verbose_name='Длительность')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Фотография')),
            ],
        ),
    ]
