# Generated by Django 4.2.7 on 2023-11-06 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_masters_photo'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.services')),
                ('speciality_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.speciality')),
            ],
        ),
    ]
