# Generated by Django 4.2.7 on 2024-04-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='duration',
            field=models.TimeField(verbose_name='Длительность'),
        ),
    ]
