# Generated by Django 4.2.7 on 2024-04-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_services_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='duration',
            field=models.DurationField(verbose_name='Длительность'),
        ),
    ]
