# Generated by Django 4.2.7 on 2024-05-04 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_alter_users_is_customer'),
        ('services', '0003_alter_services_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='duration',
            field=models.TimeField(verbose_name='Длительность'),
        ),
        migrations.CreateModel(
            name='MasterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='services.categories', verbose_name='Категория')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.masters', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Категории мастеров',
                'verbose_name_plural': 'Категории мастеров',
            },
        ),
    ]
