# Generated by Django 4.2.7 on 2024-05-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_services_duration_mastercategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
