# Generated by Django 4.2.7 on 2024-06-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_services_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='description',
        ),
        migrations.RemoveField(
            model_name='services',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='services',
            name='slug',
        ),
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
